### PR TITLE
added W3C JA leaflet data 202305 Edition

### PR DESCRIPTION
**Pull request by himorin**
no .ai data for both side, due to file size limit (50MB) of GitHub.

### CODE REVIEW

**Comment by xfq** [comment]
FWIW, Git Large File Storage allows files under 2 GB, so that might work. [jlreq](https://github.com/w3c/jlreq/issues/63) also uses it.

**Comment by xfq** [comment]
See https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage

**Comment by himorin** [comment]
> FWIW, Git Large File Storage allows files under 2 GB, so that might work. [jlreq](https://github.com/w3c/jlreq/issues/63) also uses it.

should be, with payed org...

**Comment by xfq** [comment]
From https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage#about-git-large-file-storage it seems to be free?

**Pull request merged**
