### PR TITLE
monthly summary 2023/06

### PR DESCRIPTION
**Pull request by himorin**
for review, [display at branch](https://github.com/w3ckeio/w3ckeio.github.io/blob/ms-202306/monthly-summary/202306.md)

- [x] link
- [x] missing
- [x] markdown

### CODE REVIEW

**Comment by himorin** [comment]
dpubのCRD 2件は以上の可能性あり。systeamには連絡済み。

**Comment by himorin** [comment]
Ready for review!
@naomi will check about two dpub CRD shortly, please do NOT merge while checking...

**Comment by yonaomi** [comment]
> Ready for review! @yonaomi will check about two dpub CRD shortly, please do NOT merge while checking...

@himorin it looks like 

> Ready for review! @yonaomi will check about two dpub CRD shortly, please do NOT merge while checking...

It seems other dpub CRD haven't input on the page yet. I'll wait for the update. Thanks Atsushi.

**Comment by himorin** [comment]
@yonaomi systeam fixed wrongly published CRDs. 
and page updated.

**Pull request merged**
